version: "3.8"
services:
  app:
    build: .
    volumes:
      - /Users/anyabrunwork/Projects/meow_pi:/workspace 
    command: sleep infinity
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meow_pi_development
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: